#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action=stop --log_path=systemd

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir"
fi

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

ynh_nodejs_install

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add $app --description="The news reader that doesn't know you" --log="/var/log/$app/$app.log"

#=================================================
# UPDATE APP
#=================================================
ynh_script_progression "Upgrading the app..."

pushd $install_dir
# set port in configuration file
        sed -i "/HTTP_PORT/s/[0-9]*[0-9]/$port/" package.json
        sed -i "/HTTPS_PORT/s/[0-9]*[0-9]/$port_https/" package.json
    if [ "$path" != "/" ] ; then
        sed -i "s|\$.get(\"/feed\", {|\$.get(\"feed\", {|" public/js/PTL.feed.js

    fi

	[[ -v HOME ]] && TMP_HOME=$HOME
        HOME=$(pwd)

        ynh_hide_warnings npm install --ignore-scripts
        [[ -v TMP_HOME ]] && HOME=$TMP_HOME || unset HOME
popd

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path=systemd --wait_until="Pétrolette HTTP Server running on port"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
